/*
  COLMENA-DESCRIPTION-SERVICE
  Copyright © 2024 EVIDEN
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  
  This work has been implemented within the context of COLMENA project.
*/
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: protobuf/server.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_server_proto_rawDescGZIP(), []int{0}
}

type SLAObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string            `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name    string            `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	State   string            `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
	Details []*SLAObj_Details `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *SLAObj) Reset() {
	*x = SLAObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SLAObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAObj) ProtoMessage() {}

func (x *SLAObj) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAObj.ProtoReflect.Descriptor instead.
func (*SLAObj) Descriptor() ([]byte, []int) {
	return file_protobuf_server_proto_rawDescGZIP(), []int{1}
}

func (x *SLAObj) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SLAObj) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SLAObj) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SLAObj) GetDetails() []*SLAObj_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

type InputSLAObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId string                         `protobuf:"bytes,1,opt,name=ServiceId,proto3" json:"ServiceId,omitempty"`
	Roles     []*InputSLAObj_InputSLAObjRole `protobuf:"bytes,2,rep,name=Roles,proto3" json:"Roles,omitempty"`
	Kpis      []string                       `protobuf:"bytes,3,rep,name=Kpis,proto3" json:"Kpis,omitempty"`
}

func (x *InputSLAObj) Reset() {
	*x = InputSLAObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputSLAObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSLAObj) ProtoMessage() {}

func (x *InputSLAObj) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSLAObj.ProtoReflect.Descriptor instead.
func (*InputSLAObj) Descriptor() ([]byte, []int) {
	return file_protobuf_server_proto_rawDescGZIP(), []int{2}
}

func (x *InputSLAObj) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *InputSLAObj) GetRoles() []*InputSLAObj_InputSLAObjRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *InputSLAObj) GetKpis() []string {
	if x != nil {
		return x.Kpis
	}
	return nil
}

type SLAId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *SLAId) Reset() {
	*x = SLAId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SLAId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAId) ProtoMessage() {}

func (x *SLAId) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAId.ProtoReflect.Descriptor instead.
func (*SLAId) Descriptor() ([]byte, []int) {
	return file_protobuf_server_proto_rawDescGZIP(), []int{3}
}

func (x *SLAId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SLAObj_Details struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guarantees []*SLAObj_Details_Guarantee `protobuf:"bytes,1,rep,name=guarantees,proto3" json:"guarantees,omitempty"`
}

func (x *SLAObj_Details) Reset() {
	*x = SLAObj_Details{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SLAObj_Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAObj_Details) ProtoMessage() {}

func (x *SLAObj_Details) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAObj_Details.ProtoReflect.Descriptor instead.
func (*SLAObj_Details) Descriptor() ([]byte, []int) {
	return file_protobuf_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SLAObj_Details) GetGuarantees() []*SLAObj_Details_Guarantee {
	if x != nil {
		return x.Guarantees
	}
	return nil
}

type SLAObj_Details_Guarantee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Constraint string `protobuf:"bytes,2,opt,name=Constraint,proto3" json:"Constraint,omitempty"`
}

func (x *SLAObj_Details_Guarantee) Reset() {
	*x = SLAObj_Details_Guarantee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SLAObj_Details_Guarantee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLAObj_Details_Guarantee) ProtoMessage() {}

func (x *SLAObj_Details_Guarantee) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLAObj_Details_Guarantee.ProtoReflect.Descriptor instead.
func (*SLAObj_Details_Guarantee) Descriptor() ([]byte, []int) {
	return file_protobuf_server_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *SLAObj_Details_Guarantee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SLAObj_Details_Guarantee) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

type InputSLAObj_InputSLAObjRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Kpis []string `protobuf:"bytes,2,rep,name=Kpis,proto3" json:"Kpis,omitempty"`
}

func (x *InputSLAObj_InputSLAObjRole) Reset() {
	*x = InputSLAObj_InputSLAObjRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputSLAObj_InputSLAObjRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSLAObj_InputSLAObjRole) ProtoMessage() {}

func (x *InputSLAObj_InputSLAObjRole) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSLAObj_InputSLAObjRole.ProtoReflect.Descriptor instead.
func (*InputSLAObj_InputSLAObjRole) Descriptor() ([]byte, []int) {
	return file_protobuf_server_proto_rawDescGZIP(), []int{2, 0}
}

func (x *InputSLAObj_InputSLAObjRole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InputSLAObj_InputSLAObjRole) GetKpis() []string {
	if x != nil {
		return x.Kpis
	}
	return nil
}

var File_protobuf_server_proto protoreflect.FileDescriptor

var file_protobuf_server_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x87, 0x02, 0x0a, 0x06, 0x53,
	0x4c, 0x41, 0x4f, 0x62, 0x6a, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x32, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x4c, 0x41, 0x4f,
	0x62, 0x6a, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x1a, 0x8e, 0x01, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x42, 0x0a, 0x0a, 0x67, 0x75, 0x61, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x4c, 0x41, 0x4f, 0x62, 0x6a, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x47, 0x75,
	0x61, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x65, 0x52, 0x0a, 0x67, 0x75, 0x61, 0x72, 0x61, 0x6e, 0x74,
	0x65, 0x65, 0x73, 0x1a, 0x3f, 0x0a, 0x09, 0x47, 0x75, 0x61, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x4c,
	0x41, 0x4f, 0x62, 0x6a, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x3b, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x53, 0x4c, 0x41, 0x4f, 0x62, 0x6a, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x4c,
	0x41, 0x4f, 0x62, 0x6a, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x4b, 0x70, 0x69, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x4b,
	0x70, 0x69, 0x73, 0x1a, 0x35, 0x0a, 0x0f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x4c, 0x41, 0x4f,
	0x62, 0x6a, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x70, 0x69, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x70, 0x69, 0x73, 0x22, 0x17, 0x0a, 0x05, 0x53, 0x4c,
	0x41, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x64, 0x32, 0xa0, 0x01, 0x0a, 0x06, 0x53, 0x4c, 0x41, 0x73, 0x76, 0x63, 0x12, 0x39,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x4c, 0x41, 0x12, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x4c, 0x41, 0x4f,
	0x62, 0x6a, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x53, 0x4c, 0x41, 0x4f, 0x62, 0x6a, 0x12, 0x2e, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x4c, 0x41, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x4c, 0x41, 0x49, 0x64, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x4c, 0x41, 0x4f, 0x62, 0x6a, 0x12, 0x2b, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x53, 0x4c, 0x41, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x4c, 0x41, 0x49, 0x64, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x4c, 0x41, 0x4f, 0x62, 0x6a, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_server_proto_rawDescOnce sync.Once
	file_protobuf_server_proto_rawDescData = file_protobuf_server_proto_rawDesc
)

func file_protobuf_server_proto_rawDescGZIP() []byte {
	file_protobuf_server_proto_rawDescOnce.Do(func() {
		file_protobuf_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_server_proto_rawDescData)
	})
	return file_protobuf_server_proto_rawDescData
}

var file_protobuf_server_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protobuf_server_proto_goTypes = []interface{}{
	(*Empty)(nil),                       // 0: protobuf.Empty
	(*SLAObj)(nil),                      // 1: protobuf.SLAObj
	(*InputSLAObj)(nil),                 // 2: protobuf.InputSLAObj
	(*SLAId)(nil),                       // 3: protobuf.SLAId
	(*SLAObj_Details)(nil),              // 4: protobuf.SLAObj.Details
	(*SLAObj_Details_Guarantee)(nil),    // 5: protobuf.SLAObj.Details.Guarantee
	(*InputSLAObj_InputSLAObjRole)(nil), // 6: protobuf.InputSLAObj.InputSLAObjRole
}
var file_protobuf_server_proto_depIdxs = []int32{
	4, // 0: protobuf.SLAObj.details:type_name -> protobuf.SLAObj.Details
	6, // 1: protobuf.InputSLAObj.Roles:type_name -> protobuf.InputSLAObj.InputSLAObjRole
	5, // 2: protobuf.SLAObj.Details.guarantees:type_name -> protobuf.SLAObj.Details.Guarantee
	2, // 3: protobuf.SLAsvc.CreateSLA:input_type -> protobuf.InputSLAObj
	3, // 4: protobuf.SLAsvc.DeleteSLA:input_type -> protobuf.SLAId
	3, // 5: protobuf.SLAsvc.GetSLA:input_type -> protobuf.SLAId
	2, // 6: protobuf.SLAsvc.CreateSLA:output_type -> protobuf.InputSLAObj
	1, // 7: protobuf.SLAsvc.DeleteSLA:output_type -> protobuf.SLAObj
	1, // 8: protobuf.SLAsvc.GetSLA:output_type -> protobuf.SLAObj
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_server_proto_init() }
func file_protobuf_server_proto_init() {
	if File_protobuf_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SLAObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputSLAObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SLAId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SLAObj_Details); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SLAObj_Details_Guarantee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputSLAObj_InputSLAObjRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_server_proto_goTypes,
		DependencyIndexes: file_protobuf_server_proto_depIdxs,
		MessageInfos:      file_protobuf_server_proto_msgTypes,
	}.Build()
	File_protobuf_server_proto = out.File
	file_protobuf_server_proto_rawDesc = nil
	file_protobuf_server_proto_goTypes = nil
	file_protobuf_server_proto_depIdxs = nil
}
